# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

meanByBlocks <- function(M, clu, dimensions, diagonal = "same") {
    .Call(`_kmBlock_meanByBlocks`, M, clu, dimensions, diagonal)
}

kmBlock <- function(M, clu, weights, n, nClu) {
    .Call(`_kmBlock_kmBlock`, M, clu, weights, n, nClu)
}

criterialFunction <- function(M, clu, weights, dimensions) {
    .Call(`_kmBlock_criterialFunction`, M, clu, weights, dimensions)
}

