# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

meanByBlocks <- function(M, clu, dimensions, n, diagonal = "ignore") {
    .Call(`_kmBlock_meanByBlocks`, M, clu, dimensions, n, diagonal)
}

kmBlock <- function(M, clu, weights, n, nClu, p_sDiagonal = "ignore") {
    .Call(`_kmBlock_kmBlock`, M, clu, weights, n, nClu, p_sDiagonal)
}

critFunction <- function(M, clu, weights, dimensions, n, p_sDiagonal = "ignore") {
    .Call(`_kmBlock_critFunction`, M, clu, weights, dimensions, n, p_sDiagonal)
}

