// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// test
Rcpp::NumericVector test(const arma::Cube<double> M, const Rcpp::NumericVector clu, const arma::Cube<double> weights, const Rcpp::NumericVector n, const Rcpp::NumericVector nClu);
RcppExport SEXP _kmBlock_test(SEXP MSEXP, SEXP cluSEXP, SEXP weightsSEXP, SEXP nSEXP, SEXP nCluSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::Cube<double> >::type M(MSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type clu(cluSEXP);
    Rcpp::traits::input_parameter< const arma::Cube<double> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type n(nSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type nClu(nCluSEXP);
    rcpp_result_gen = Rcpp::wrap(test(M, clu, weights, n, nClu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kmBlock_test", (DL_FUNC) &_kmBlock_test, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_kmBlock(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
