// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "kmBlock_types.h"
#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// meanByBlocks
Rcpp::List meanByBlocks(const Array& M, const IVector& clu, const int dimensions, const IVector& n, const std::string diagonal);
RcppExport SEXP _kmBlock_meanByBlocks(SEXP MSEXP, SEXP cluSEXP, SEXP dimensionsSEXP, SEXP nSEXP, SEXP diagonalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Array& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const IVector& >::type clu(cluSEXP);
    Rcpp::traits::input_parameter< const int >::type dimensions(dimensionsSEXP);
    Rcpp::traits::input_parameter< const IVector& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::string >::type diagonal(diagonalSEXP);
    rcpp_result_gen = Rcpp::wrap(meanByBlocks(M, clu, dimensions, n, diagonal));
    return rcpp_result_gen;
END_RCPP
}
// kmBlock
Rcpp::List kmBlock(const Array& M, const IVector& clu, const Array& weights, const IVector& n, const IVector& nClu, const std::string& p_sDiagonal);
RcppExport SEXP _kmBlock_kmBlock(SEXP MSEXP, SEXP cluSEXP, SEXP weightsSEXP, SEXP nSEXP, SEXP nCluSEXP, SEXP p_sDiagonalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Array& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const IVector& >::type clu(cluSEXP);
    Rcpp::traits::input_parameter< const Array& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const IVector& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const IVector& >::type nClu(nCluSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type p_sDiagonal(p_sDiagonalSEXP);
    rcpp_result_gen = Rcpp::wrap(kmBlock(M, clu, weights, n, nClu, p_sDiagonal));
    return rcpp_result_gen;
END_RCPP
}
// critFunction
double critFunction(const Array& M, const IVector& clu, const Array& weights, const int dimensions, const IVector& n, const std::string& p_sDiagonal);
RcppExport SEXP _kmBlock_critFunction(SEXP MSEXP, SEXP cluSEXP, SEXP weightsSEXP, SEXP dimensionsSEXP, SEXP nSEXP, SEXP p_sDiagonalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Array& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const IVector& >::type clu(cluSEXP);
    Rcpp::traits::input_parameter< const Array& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const int >::type dimensions(dimensionsSEXP);
    Rcpp::traits::input_parameter< const IVector& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type p_sDiagonal(p_sDiagonalSEXP);
    rcpp_result_gen = Rcpp::wrap(critFunction(M, clu, weights, dimensions, n, p_sDiagonal));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_kmBlock_meanByBlocks", (DL_FUNC) &_kmBlock_meanByBlocks, 5},
    {"_kmBlock_kmBlock", (DL_FUNC) &_kmBlock_kmBlock, 6},
    {"_kmBlock_critFunction", (DL_FUNC) &_kmBlock_critFunction, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_kmBlock(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
